// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geoitayicqjthripopoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdlb2l0YXlpY3FqdGhyaXBvcG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MDgzNTEsImV4cCI6MjA3MDk4NDM1MX0.gSKnLfUVvN3usSQ8fdqZJCeGt2mWrdEwqDptuU_Xt1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});